version: "3.3"
services:
    wordpress:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8888:80"
        depends_on:
            - db
        environment:
            WORDPRESS_DB_HOST: "db:3306"
        env_file: .env
        volumes:
            - ./src:/var/www/html/wp-content/themes/my-theme
            - ./devenv/plugins:/var/www/html/wp-content/plugins
            - ./devenv/languages:/var/www/html/wp-content/languages
            - ./tmp/wp-content-uploads:/var/www/html/wp-content/uploads
    db:
        image: mysql:latest
        env_file: .env
        volumes:
            - db-data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        env_file: .env
        links:
            - db
        ports:
             - 8080:80
        volumes:
             - ./tmp/phpmyadmin-sessions:/sessions
volumes:
    db-data:
        driver: local

